name: CD Rails & Svelte

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version for increase tag
        required: true
        options:
          - major
          - minor
          - patch
      environment:
        description: Environment to run CD
        type: choice
        required: true
        options:
          - stg
          - prod

jobs:
  build_api_push_gcr_stg:
    name: Build and Push to GCP
    if: ${{ inputs.environment == 'stg' }}
    runs-on: ubuntu-16.04
    defaults:
      run:
        working-directory: rails-api
    env:
      IMAGE_NAME: api-stg
      PROJECT_ID: github-action-361002
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:lastest .

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          cd ../github/workflows 
          bash ./scripts/git_update.sh -v ${{ inputs.version }}

      - name: Push Docker Image to GCR
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
