name: Rails-CI

on: [push]
  # push:
    # branches:
    #   - 'releases**'
  
  # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        env:
          POSTGRES_PASSWORD: password
        image: postgres:14.5-alpine
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true

    - name: Bundle & Prepare database
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        PGPASSWORD: password
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        cd rails-api
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:prepare

    - name: Run rubocop
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        PGPASSWORD: password
        RAILS_ENV: test
      run: |
        cd rails-api
        bundle exec rubocop

    - name: Run tests
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        PGPASSWORD: password
        RAILS_ENV: test
      run: |
        cd rails-api
        bundle exec rails test

    - name: Verify Build
      run: |
        cd rails-api
        docker build -t api:lastest .

