name: Rails Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        env:
          POSTGRES_PASSWORD: password
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1.2
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Prepare
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        PGPASSWORD: password
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        cd rails-api
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rubocop
        bundle exec rails test

